name: Release Version
on:
  push:
    tags:
      - 'v*'
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            Bank/Bank.WebApi/bin/Release/net8.0/Bank.WebApi.dll
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
